version: '3.5'

services:
    diagnostic:
        build: ./
        container_name: 'diagnostic'
        tty: true
        environment:
            RABBITMQ_HOST: 'rabbitmq'
            DATABASE_HOST: 'diagnostic-mysql'
            REDIS_HOST: 'diagnostic-redis'
            MAILER_HOST: 'diagnostic-mailcatcher'
            ELASTICSEARCH_HOST: 'elasticsearch'
            MONGO_PROTOCOL: 'mongodb'
            MONGO_HOST: 'diagnostic-mongo'
            MONGO_USER: 'root'
            MONGO_PASSWORD: 'root'
            MONGO_DB: 'diagnostic'
            MONGO_COLLECTION: 'test'
            AWS_DYNAMODB_ENDPOINT: 'http://dynamodb:8000'
            OPENSEARCH_HOST: 'opensearch'
        volumes:
            - './:/code'
        networks:
            - diagnostic

    rabbitmq:
        image: rabbitmq:management
        container_name: 'diagnostic-rabbitmq'
        networks:
            - diagnostic

    mysql:
        image: mysql:8.0
        container_name: 'diagnostic-mysql'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: diagnostic
        networks:
            - diagnostic

    redis:
        image: redis:alpine
        container_name: 'diagnostic-redis'
        networks:
            - diagnostic

    mailcatcher:
        image: schickling/mailcatcher
        container_name: 'diagnostic-mailcatcher'
        networks:
            - diagnostic

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        container_name: 'diagnostic-elasticsearch'
        environment:
            - 'discovery.type=single-node'
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - diagnostic

    dynamodb:
        image: amazon/dynamodb-local
        container_name: 'diagnostic-dynamodb'
        restart: always
        command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb']
        networks:
            - diagnostic

    mongo:
        image: mongo
        container_name: 'diagnostic-mongo'
        restart: always
        environment:
            MONGO_INITDB_DATABASE: admin
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks:
            - diagnostic

    opensearch:
        image: opensearchproject/opensearch:2.4.0
        container_name: 'diagnostic-opensearch'
        environment:
            - 'discovery.type=single-node'
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "DISABLE_SECURITY_PLUGIN=true"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - diagnostic

networks:
    diagnostic:
        driver: bridge
        name: diagnostic
