version: '3.5'

services:
    diagnostic:
        build: ./
        container_name: 'diagnostic'
        tty: true
        environment:
            RABBITMQ_HOST: 'diagnostic-rabbitmq'
            DATABASE_HOST: 'diagnostic-mysql'
            REDIS_HOST: 'diagnostic-redis'
            MAILER_HOST: 'diagnostic-mailcatcher'
            ELASTICSEARCH_HOST: 'diagnostic-elasticsearch'
        volumes:
            - './:/code'
        networks:
            - diagnostic

    rabbitmq:
        image: rabbitmq:management
        container_name: 'diagnostic-rabbitmq'
        networks:
            - diagnostic

    mysql:
        image: mysql:5.7
        container_name: 'diagnostic-mysql'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: diagnostic
        networks:
            - diagnostic

    redis:
        image: redis:alpine
        container_name: 'diagnostic-redis'
        networks:
            - diagnostic

    mailcatcher:
        image: schickling/mailcatcher
        container_name: 'diagnostic-mailcatcher'
        networks:
            - diagnostic

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
        container_name: 'diagnostic-elasticsearch'
        networks:
            - diagnostic

networks:
    diagnostic:
        driver: bridge
        name: diagnostic
